### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by enryH** [enryH/cbpp_info#19]
To write:
- [ ] Nordic Countries Registration: [`_pages/nordic_countries.md`](https://github.com/enryH/cbpp_info/blob/master/_pages/register_nordic.md)
- [ ] summary sites linking information: [`_pages/register.md`](https://github.com/enryH/cbpp_info/tree/master/_pages/register.md),  [`_pages/arriving_before.md`](https://github.com/enryH/cbpp_info/tree/master/_pages/arriving_before.md), [`_pages/arriving_after.md`](https://github.com/enryH/cbpp_info/tree/master/_pages/arriving_before.md)

To discuss:
- [ ] landing pages
- [ ] maybe additional [`_pages/topics.md`](https://github.com/enryH/cbpp_info/tree/master/_pages/topics.md)
 pages

**Comment by enryH** [comment]
- [ ] check lifehack arriving in copenhagen website
- [ ] make funny quizzes
- [ ] add bullet points summarizing/ linking the main steps of each page (if applicable)
- [ ] decide about a (most) uniform structure of a page
- [ ] check formatting and fix issues on final website
   - [x] Sidebar: Make all capital letters
- [ ] add specific time from september with Todos
